# Generated by Django 4.2.7 on 2023-11-28 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import noise_detection_api.resource.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('audio_file', models.FileField(error_messages={'required': 'Please select an audio file to analyse'}, upload_to='audio_files/', validators=[noise_detection_api.resource.validator.check_extension, noise_detection_api.resource.validator.check_mime_type, noise_detection_api.resource.validator.check_file_size], verbose_name='Select Audio FIle')),
                ('audio_file_size', models.FloatField(default=0.0)),
                ('audio_file_duration', models.CharField(default='', max_length=300)),
                ('audio_file_type', models.CharField(blank=True, max_length=300)),
                ('noise_density', models.FloatField(default=0.0)),
                ('category', models.CharField(blank=True, max_length=300)),
                ('user_ip_address', models.GenericIPAddressField(null=True, unpack_ipv4=True)),
                ('gps_location', models.TextField(blank=True)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
                ('video_evidence', models.FileField(error_messages={'required': 'Please select an Video file for evidence'}, upload_to='video_files/', validators=[noise_detection_api.resource.validator.check_video_extension, noise_detection_api.resource.validator.check_file_size], verbose_name='Select Video FIle')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='date logged')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
