# Generated by Django 4.2.7 on 2023-11-28 14:24

from django.db import migrations, models
import noise_detection_api.resource.validator


class Migration(migrations.Migration):

    dependencies = [
        ('noise_detection_api', '0002_alter_audioanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioanalysis',
            name='mel_graph',
            field=models.FileField(blank=True, upload_to='graph_files/', validators=[noise_detection_api.resource.validator.check_extension, noise_detection_api.resource.validator.check_mime_type, noise_detection_api.resource.validator.check_file_size], verbose_name='Select Graph Image'),
        ),
        migrations.AlterField(
            model_name='audioanalysis',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio_files/', validators=[noise_detection_api.resource.validator.check_extension, noise_detection_api.resource.validator.check_mime_type, noise_detection_api.resource.validator.check_file_size], verbose_name='Select Audio FIle'),
        ),
    ]
