# Generated by Django 4.2.7 on 2023-11-28 16:47

from django.db import migrations, models
import noise_detection_api.resource.validator


class Migration(migrations.Migration):

    dependencies = [
        ('noise_detection_api', '0004_alter_audioanalysis_mel_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioanalysis',
            name='mel_graph',
            field=models.FileField(blank=True, upload_to='graph_files/', validators=[noise_detection_api.resource.validator.check_image_extension, noise_detection_api.resource.validator.check_file_size], verbose_name='Select Graph Image'),
        ),
    ]
